// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhWeeKQwMKvbgYFePvsqjNgph4_SfpKEA',
    appId: '1:583555396936:web:f8a9d4959e9103d7cc6f7d',
    messagingSenderId: '583555396936',
    projectId: 'kindergarten-5cdbe',
    authDomain: 'kindergarten-5cdbe.firebaseapp.com',
    storageBucket: 'kindergarten-5cdbe.appspot.com',
    measurementId: 'G-WHYHTRJM2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASVuQaqdyBeZyGBFxiB3MVxncfeJcNEO4',
    appId: '1:583555396936:android:50551e289ce1636ccc6f7d',
    messagingSenderId: '583555396936',
    projectId: 'kindergarten-5cdbe',
    storageBucket: 'kindergarten-5cdbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfMhzesGA9o5BCyNWrwFP1jHfi1pVMBw',
    appId: '1:583555396936:ios:9537bbdddc0c9372cc6f7d',
    messagingSenderId: '583555396936',
    projectId: 'kindergarten-5cdbe',
    storageBucket: 'kindergarten-5cdbe.appspot.com',
    iosClientId: '583555396936-mp9uktbc8db42md1hj1bv6vdktgmme1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindergarten1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvfMhzesGA9o5BCyNWrwFP1jHfi1pVMBw',
    appId: '1:583555396936:ios:9537bbdddc0c9372cc6f7d',
    messagingSenderId: '583555396936',
    projectId: 'kindergarten-5cdbe',
    storageBucket: 'kindergarten-5cdbe.appspot.com',
    iosClientId: '583555396936-mp9uktbc8db42md1hj1bv6vdktgmme1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindergarten1',
  );
}
